#readthedocs uses defaults rather than conda-forge
name: intake-stac
channels:
  - defaults
dependencies:
  - python=3.7
  - fsspec
  - geopandas
  - intake
  - intake-xarray
  - mock
  - pillow
  - pip
  - pytest-cov
  - rasterio
  - sphinx
  - sphinx_rtd_theme
  - xarray
  - pip:
      - sat-stac
      - .. #installs intake-stac from root folder
