name: intake-stac
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - aiohttp
  - fsspec
  - geopandas
  - intake
  - intake-xarray
  - ipython
  - mock
  - nbsphinx
  - numpydoc
  - pillow
  - pip
  - pystac
  - pytest-cov
  - rasterio
  - sat-search
  - scikit-image
  - sphinx
  - sphinx_rtd_theme
  - xarray
  - pip:
      - ../ #installs intake-stac from root folder
