name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  checks:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install intake-stac
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    - name: Install doc dependencies
      run: python -m pip install -r docs/requirements.txt -r requirements.txt

    - name: Build docs
      run: |
        cd docs
        make html
